### ISSUE TITLE
Find a way to differentiate training course illustrations

### ISSUE THREAD

**Issue by Mogztter** [neo4j-documentation/docs-refresh#62]
Currently, we are using a set of 7 images but we have 11 (and counting) courses so some images are duplicated:

![courses](https://user-images.githubusercontent.com/333276/100267009-09e92f00-2f53-11eb-9435-3b5f52e6f413.png)

We should find a way to differentiate them.

@ElaineRosenberg suggested to add the title on the image. If so, we should probably remove the title from the card as the information will be seen twice:

![yo](https://user-images.githubusercontent.com/333276/100267100-29805780-2f53-11eb-9a54-62526b7513d9.png)

Another idea would be to apply gradients to create variations of the same image:

![gradient](https://user-images.githubusercontent.com/333276/100267149-41f07200-2f53-11eb-9529-a5abdf09c8cc.png)

**Comment by ElaineRosenberg** [comment]
Gradients already exist for the 3.5 courses vs the 4.0 courses and I would want to keep it that way for now.

My preference is to overlay the title on the image and remove the title from the card.

**Comment by Mogztter** [comment]
Here's my proposal:

I've replaced the title with the short description and the title is now dynamically added over the background image:

![title-description](https://user-images.githubusercontent.com/333276/100342768-c20fe980-2fde-11eb-8ea0-8375e9a3c46e.png)
